version: '3.4'

networks:
  deploy-guide-dev:
    driver: bridge
services:
  vkinternship:
    container_name: vkinternship
    image: ${DOCKER_REGISTRY-}vkinternship
    build:
      context: .
      dockerfile: VKInternship/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: VKInternshipDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 138
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: